language: generic
sudo : required
services:
  - docker



before_install:
  - docker build -t james/docker-react -f Dockerfile.dev .



script:
  - docker run -e CI=true james/docker-react npm run test